id: I90999C36
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:10:46+00:00'
last_modified: '2022-06-08T11:28:27.374555+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5966
  title: གསུང་འབུམ། བྱམས་པ་ཆོས་གྲགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    19EF:
      image_group_id: I1KG5980
      title: ''
      total_pages: 2
      order: 1
      base_file: 19EF.txt
    '7165':
      image_group_id: I1KG5981
      title: ''
      total_pages: 454
      order: 2
      base_file: 7165.txt
    '1583':
      image_group_id: I1KG5982
      title: ''
      total_pages: 402
      order: 3
      base_file: 1583.txt
    01DD:
      image_group_id: I1KG5983
      title: ''
      total_pages: 438
      order: 4
      base_file: 01DD.txt
    '0440':
      image_group_id: I1KG5984
      title: ''
      total_pages: 470
      order: 5
      base_file: 0440.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
